export enum TODOS_OPERATIONS {
  "CREATE_TODO" = "CREATE_TODO",
  "LIST_TODOS" = "LIST_TODOS",
  "FIND_TODO" = "FIND_TODO",
  "UPDATE_TODO" = "UPDATE_TODO",
  "PATCH_TODO" = "PATCH_TODO",
  "DELETE_TODO" = "DELETE_TODO",
}
